# Configurations
title:            Colofón Podcast
longtitle:        Colofón Podcast
author:           Roberto Mateu
email:            rmateu@gmail.com
description: Un podcast de entrevistas a personas creadoras y las herramientas que usan para ser productivas.

version:          1.0
gitbook_version:  3.2.3

url:              'http://colofon.mateu.me'
baseurl:          '/'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6  
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

# Statics 
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  # - jemoji
  - jekyll-feed
